apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: hand-of-fate
data:
  mail-host:     smtp.example.com
  frontend-url:  https://fate.example.com
  otel-endpoint: http://otel-collector:4318
